name: Tyler Dilts
favicon: null
layout_spectrum: 0.9207615815103054
typography_spectrum: 0.26925167185254395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4a4a4a'
    - '#f7fefe'
    - '#87a0a4'
    - '#eee245'
  brandStrength: 0.5
  lightness: 0.2890417368616909
  saturation: 0.5
  rhythmicContrast: 0.7866963914129883
purpose: []
